### ISSUE TITLE
[question] missing subtitles for Cloud service strategies in COSS

### ISSUE THREAD

**Issue by zhicheng-ning** [X-lab2017/oss101-awesome-list#10]
As shown below, COSS has eight topics, but subtitle of Cloud service strategies  doesn's exist in https://github.com/X-lab2017/oss101-awesome-list/tree/main/Commercial%20Open%20Source%20Startups%20(COSS).

![image](https://user-images.githubusercontent.com/39022409/182067076-523ea6cb-921c-4c1f-9f7e-a03e9c9df8c5.png)

**Comment by bifenglin** [comment]
what I find the course is in https://github.com/X-lab2017/open-wonderland/issues/133. So what the course should be? @will-ww @birdfly

**Comment by zhicheng-ning** [comment]
It's  cool~, I want to know whether exists a proper workflow to handle subtitle last year. Maybe I can refer to it.
